export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Meals } from './Meals'
export { default as Navigation } from './Navigation'
export { default as Statistics } from './Statistics'