export { default as CloseSvg } from './close.svg'
export { default as HomeSvg } from './home.svg'
export { default as ProfileSvg } from './profile.svg'
export { default as SearchSvg } from './search.svg'
export { default as StatisticsSvg } from './statistics.svg'
export { default as TasksSvg } from './tasks.svg'